# Generated by Django 5.0 on 2026-01-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_avatar_file'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='accounts_pa_user_id_c9188d_idx',
            old_name='accounts_pa_user_id_4d5553_idx',
        ),
    ]
