# Generated by Django 5.0 on 2026-01-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_accounts_pa_user_id_4d5553_idx_accounts_pa_user_id_c9188d_idx'),
        ('accounts', '0008_user_birth_date'),
    ]

    operations = [
    ]
