# Generated by Django 5.0.7 on 2026-01-28 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier (e.g. from react-native-device-info)', max_length=255, unique=True)),
                ('device_name', models.CharField(help_text='e.g. iPhone 13, Samsung Galaxy S21', max_length=255)),
                ('fcm_token', models.CharField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', max_length=255, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
