# Generated by Django 5.0.7 on 2026-01-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='JWT refresh token for this device session', null=True),
        ),
    ]
