# Generated by Django 5.0.7 on 2026-01-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='chat_chatro_updated_fe8347_idx',
            old_name='chat_chatro_updated_e5c7e5_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_room_id_5feac5_idx',
            old_name='chat_messag_room_id_19a7e9_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_room_id_ab1c01_idx',
            old_name='chat_messag_room_id_e8f0ae_idx',
        ),
    ]
