# Generated by Django 5.0.7 on 2026-01-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
