# Generated by Django 5.0.7 on 2026-01-28 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_file_message_file_name_message_file_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('voice', 'Voice'), ('video', 'Video')], default='voice', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ringing', 'Ringing'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('ended', 'Ended'), ('rejected', 'Rejected'), ('missed', 'Missed'), ('busy', 'Busy'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('agora_channel', models.CharField(blank=True, max_length=255)),
                ('agora_token', models.CharField(blank=True, max_length=512)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='chat.chatroom')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room', '-created_at'], name='chat_call_room_id_6b50c4_idx'), models.Index(fields=['caller', 'status'], name='chat_call_caller__9c00dd_idx'), models.Index(fields=['callee', 'status'], name='chat_call_callee__89c8fb_idx')],
            },
        ),
    ]
