# Generated by Django (Manual)

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_add_call_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('file', 'File'), ('call', 'Call'), ('system', 'System')], default='text', max_length=20),
        ),
    ]
