# Generated by Django 5.0.7 on 2026-01-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='short_description',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='idealike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
