# Generated by Django 5.0.7 on 2026-01-19 12:17

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_comment_created_at_alter_idea_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Tag can only contain letters, numbers, hyphens, and underscores', regex='^[a-zA-Z0-9-_]+$')]),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['-created_at'], name='ideas_idea_created_f8487a_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['-views_count'], name='ideas_idea_views_c_93ed54_idx'),
        ),
    ]
