# Generated by Codex on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0007_comment_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="title_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="idea",
            name="short_description_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="idea",
            name="full_description_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="idea",
            name="category_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="comment",
            name="body_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="publiccomment",
            name="body_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
