# Generated by Django 5.0.7 on 2026-01-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_comment_is_pinned'),
        ('ideas', '0008_i18n_fields'),
    ]

    operations = [
    ]
