# Generated by Django 5.0.7 on 2026-01-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='idea-images/'),
        ),
    ]
